apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-landing
  namespace: argocd
spec:
  source:
    path: pos-landing
    repoURL: https://github.com/gdurdaneta/argocdexamples.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default

