apiVersion: v1
kind: Service
metadata:
  name: pos-landing
  namespace: "default"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pos-landing
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pos-landing"
  namespace: "default"
  labels:
    app: "pos-landing"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pos-landing"
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: "pos-landing"
    spec:
      affinity:
        nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: devops-control
              operator: NotIn
              values:
              - "true"
      containers:
      - name: "pos-landing"
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        readinessProbe:
            httpGet:
                path: /gke_health
                port: 80
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
        livenessProbe:
            httpGet:
                path: /gke_health
                port: 80
            failureThreshold: 3
            initialDelaySeconds: 5
            # Allow sufficient amount of time (180 seconds = periodSeconds * failureThreshold)
            # for the registered shutdown handlers to run to completion.
            periodSeconds: 30
            successThreshold: 1
            # Setting a very low timeout value (e.g. 1 second) can cause false-positive
            # checks and service interruption.
            timeoutSeconds: 5
        #image: "gcr.io/dataflow-chiper/empresarios.chiper.co/develop:22"
        image: "us.gcr.io/dataflow-chiper/pos-landing:latest"
        volumeMounts:
        - name: "config-nginx"
          mountPath: "/etc/nginx/conf.d"
      volumes:
      - name: "config-nginx"
        configMap:
          name: "default.conf"        
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pos-landing-hpa"
  namespace: "default"
  labels:
    app: "pos-landing"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pos-landing"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: "memory"
      targetAverageUtilization: 60
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 60
